import * as fs from 'fs';
import * as path from 'path';

export async function generateTypeScriptProject(projectPath: string, projectName: string) {
    
    // ================================
    // CRIAR PASTAS PRIMEIRO
    // ================================
    const folders = [
        'src/controllers', 'src/models', 'src/services', 'src/repositories',
        'src/middleware', 'src/config', 'src/utils', 'src/dto', 'src/validators', 'src/routes',
        'src/errors', 'src/events', 'src/jobs', 'src/mails', 'src/subscribers',
        'public/css', 'public/js', 'public/images', 'public/uploads',
        'tests/unit', 'tests/integration', 'tests/e2e',
        'docs/api', 'docs/guides',
        'logs', 'tmp', 'scripts'
    ];
    
    folders.forEach(folder => {
        fs.mkdirSync(path.join(projectPath, folder), { recursive: true });
    });

    // ================================
    // PACKAGE.JSON
    // ================================
    const packageJson = {
        name: projectName,
        version: "1.0.0",
        description: `Generated by Constellation CLI`,
        main: "dist/index.js",
        scripts: { 
            "start": "node dist/index.js",
            "dev": "ts-node-dev --respawn src/index.ts",
            "build": "tsc",
            "clean": "rm -rf dist",
            "test": "jest",
            "test:watch": "jest --watch",
            "lint": "eslint src/**/*.ts",
            "lint:fix": "eslint src/**/*.ts --fix",
            "format": "prettier --write \"src/**/*.ts\"",
            "type-check": "tsc --noEmit",
            "prepare": "npm run build"
        },
        dependencies: {
            "express": "^4.18.2",
            "mysql2": "^3.6.0",
            "bcrypt": "^5.1.0",
            "jsonwebtoken": "^9.0.0",
            "express-rate-limit": "^7.1.0",
            "cors": "^2.8.5",
            "dotenv": "^16.3.0",
            "helmet": "^7.1.0",          
            "compression": "^1.7.4",     
            "morgan": "^1.10.0",
            "express-async-errors": "^3.1.1",
            "zod": "^3.22.4",
            "uuid": "^9.0.1",
            "dayjs": "^1.11.10",
            "axios": "^1.6.2",
            "multer": "^1.4.5-lts.1",
            "nodemailer": "^6.9.7",
            "bull": "^4.11.5",
            "redis": "^4.6.12",
            "winston": "^3.11.0"
        },
        devDependencies: {
            "@types/express": "^4.17.21",
            "@types/bcrypt": "^5.0.0",
            "@types/jsonwebtoken": "^9.0.0",
            "@types/cors": "^2.8.17",
            "@types/node": "^20.0.0",
            "@types/morgan": "^1.9.9",
            "@types/compression": "^1.7.5",
            "@types/multer": "^1.4.11",
            "@types/nodemailer": "^6.4.14",
            "@types/uuid": "^9.0.7",
            "ts-node": "^10.9.0",
            "ts-node-dev": "^2.0.0",
            "typescript": "^5.0.0",
            "@typescript-eslint/eslint-plugin": "^6.0.0",
            "@typescript-eslint/parser": "^6.0.0",
            "eslint": "^8.55.0",
            "prettier": "^3.1.0",
            "jest": "^29.7.0",
            "@types/jest": "^29.5.8",
            "ts-jest": "^29.1.1",
            "supertest": "^6.3.3",
            "@types/supertest": "^2.0.16"
        },
        keywords: ["api", "rest", "backend", "typescript", "express"],
        author: "",
        license: "MIT"
    };
    fs.writeFileSync(path.join(projectPath, 'package.json'), JSON.stringify(packageJson, null, 2));

    // ================================
    // TSCONFIG.JSON
    // ================================
    const tsconfig = {
        compilerOptions: {
            target: "ES2020",
            module: "commonjs",
            outDir: "./dist",
            rootDir: "./src",
            strict: true,
            esModuleInterop: true,
            skipLibCheck: true,
            forceConsistentCasingInFileNames: true,
            resolveJsonModule: true,
            removeComments: true,
            noImplicitReturns: true,
            noUnusedLocals: true,
            noUnusedParameters: true,
            baseUrl: ".",
            paths: {
                "@/*": ["src/*"],
                "@controllers/*": ["src/controllers/*"],
                "@models/*": ["src/models/*"],
                "@services/*": ["src/services/*"],
                "@utils/*": ["src/utils/*"],
                "@config/*": ["src/config/*"]
            }
        },
        include: ["src/**/*"],
        exclude: ["node_modules", "dist", "tests"]
    };
    fs.writeFileSync(path.join(projectPath, 'tsconfig.json'), JSON.stringify(tsconfig, null, 2));

    // ================================
    // JEST.CONFIG.JS
    // ================================
    const jestConfig = `module.exports = {
    preset: 'ts-jest',
    testEnvironment: 'node',
    roots: ['<rootDir>/tests'],
    testMatch: ['**/*.test.ts'],
    collectCoverageFrom: [
        'src/**/*.ts',
        '!src/**/*.d.ts'
    ],
    coverageDirectory: 'coverage',
    moduleNameMapper: {
        '^@/(.*)$': '<rootDir>/src/$1'
    }
};`;
    fs.writeFileSync(path.join(projectPath, 'jest.config.js'), jestConfig);

    // ================================
    // .ESLINTRC.JS
    // ================================
    const eslintConfig = `module.exports = {
    parser: '@typescript-eslint/parser',
    extends: [
        'plugin:@typescript-eslint/recommended'
    ],
    parserOptions: {
        ecmaVersion: 2020,
        sourceType: 'module'
    },
    rules: {
        '@typescript-eslint/no-explicit-any': 'warn',
        '@typescript-eslint/no-unused-vars': 'error',
        'no-console': 'off'
    }
};`;
    fs.writeFileSync(path.join(projectPath, '.eslintrc.js'), eslintConfig);

    // ================================
    // .PRETTIERRC
    // ================================
    const prettierConfig = `{
    "semi": true,
    "trailingComma": "es5",
    "singleQuote": true,
    "printWidth": 100,
    "tabWidth": 2
}`;
    fs.writeFileSync(path.join(projectPath, '.prettierrc'), prettierConfig);

    // ================================
    // .ENV FILE
    // ================================
    const envContent = `NODE_ENV=development
PORT=3000
APP_NAME=${projectName}
APP_URL=http://localhost:3000

DB_HOST=localhost
DB_PORT=3306
DB_USER=root
DB_PASSWORD=root
DB_NAME=myapp

JWT_SECRET=mysecretkey
JWT_EXPIRES_IN=7d

REDIS_HOST=localhost
REDIS_PORT=6379
REDIS_PASSWORD=

MAIL_HOST=smtp.gmail.com
MAIL_PORT=587
MAIL_USER=your-email@gmail.com
MAIL_PASSWORD=your-password
MAIL_FROM=noreply@${projectName}.com

CORS_ORIGIN=http://localhost:3000
RATE_LIMIT_WINDOW=15
RATE_LIMIT_MAX=100

LOG_LEVEL=debug
`;
    fs.writeFileSync(path.join(projectPath, '.env'), envContent);
    fs.writeFileSync(path.join(projectPath, '.env.example'), envContent.replace(/=.*/g, '='));

    // ================================
    // SERVER.TS (INDEX.TS COMPLETO)
    // ================================
    const serverContent = `import express, { Request, Response, NextFunction } from 'express';
import mysql from 'mysql2/promise';
import bcrypt from 'bcrypt';
import jwt from 'jsonwebtoken';
import rateLimit from 'express-rate-limit';
import cors from 'cors';
import dotenv from 'dotenv';
import path from 'path';
import helmet from 'helmet';
import compression from 'compression';
import morgan from 'morgan';
import 'express-async-errors';

dotenv.config();

const app = express();
const PORT = process.env.PORT || 3000;

// Middlewares
app.use(helmet());
app.use(compression());
app.use(cors({
    origin: process.env.CORS_ORIGIN || '*',
    credentials: true
}));
app.use(morgan('combined'));
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use(express.static(path.join(__dirname, '../public')));

// Rate limiting
const limiter = rateLimit({
    windowMs: (parseInt(process.env.RATE_LIMIT_WINDOW) || 15) * 60 * 1000,
    max: parseInt(process.env.RATE_LIMIT_MAX) || 100,
    message: { error: 'Too many requests, please try again later.' }
});
app.use('/api/', limiter);

// Database connection pool
const pool = mysql.createPool({
    host: process.env.DB_HOST || 'localhost',
    port: parseInt(process.env.DB_PORT) || 3306,
    user: process.env.DB_USER || 'root',
    password: process.env.DB_PASSWORD || '',
    database: process.env.DB_NAME || 'myapp',
    waitForConnections: true,
    connectionLimit: 10,
    queueLimit: 0,
    enableKeepAlive: true,
    keepAliveInitialDelay: 0
});

// Test database connection
pool.getConnection()
    .then(connection => {
        console.log('✅ Database connected successfully');
        connection.release();
    })
    .catch(err => {
        console.error('❌ Database connection failed:', err.message);
    });

// Routes
app.get('/', (req: Request, res: Response) => {
    res.json({ 
        message: 'API is running!', 
        version: '1.0.0',
        environment: process.env.NODE_ENV || 'development',
        endpoints: {
            health: 'GET /health',
            api: 'GET /api',
            docs: 'GET /docs'
        }
    });
});

app.get('/health', (req: Request, res: Response) => {
    res.json({ 
        status: 'ok', 
        timestamp: new Date().toISOString(),
        uptime: process.uptime()
    });
});

app.get('/api', (req: Request, res: Response) => {
    res.json({ message: 'API v1 - Working!' });
});

// 404 handler
app.use((req: Request, res: Response) => {
    res.status(404).json({ 
        error: 'Route not found',
        path: req.originalUrl
    });
});

// Global error handler
app.use((err: any, req: Request, res: Response, next: NextFunction) => {
    console.error('Error:', err.stack);
    const status = err.status || 500;
    const message = err.message || 'Internal server error';
    
    res.status(status).json({ 
        error: message,
        status,
        timestamp: new Date().toISOString()
    });
});

// Start server
const server = app.listen(PORT, () => {
    console.log(\`🚀 Server running on port \${PORT}\`);
    console.log(\`🔗 http://localhost:\${PORT}\`);
});

// Graceful shutdown
process.on('SIGTERM', () => {
    console.log('SIGTERM signal received: closing HTTP server');
    server.close(() => {
        console.log('HTTP server closed');
        pool.end().then(() => {
            console.log('Database connection pool closed');
            process.exit(0);
        });
    });
});

export { app, pool, server };`;
    fs.writeFileSync(path.join(projectPath, 'src/index.ts'), serverContent);

    // ================================
    // BACKEND STRUCTURE (EMPTY FILES)
    // ================================
    
    // Controllers
    const controllers = ['HomeController.ts', 'UserController.ts', 'AuthController.ts'];
    controllers.forEach(file => {
        const content = `import { Request, Response } from 'express';\n\nexport class ${file.replace('.ts', '')} {\n    // TODO: Implement methods\n    \n    async index(req: Request, res: Response) {\n        return res.json({ message: '${file} working' });\n    }\n}\n`;
        fs.writeFileSync(path.join(projectPath, 'src/controllers', file), content);
    });

    // Models
    const models = ['UserModel.ts', 'ProductModel.ts', 'AuthModel.ts'];
    models.forEach(file => {
        const content = `export interface ${file.replace('Model.ts', '')} {\n    id: number;\n    created_at: Date;\n    updated_at: Date;\n    // TODO: Add fields\n}\n`;
        fs.writeFileSync(path.join(projectPath, 'src/models', file), content);
    });

    // Services
    const services = ['UserService.ts', 'AuthService.ts', 'ProductService.ts'];
    services.forEach(file => {
        const content = `export class ${file.replace('.ts', '')} {\n    // TODO: Implement business logic\n    \n    async execute(data: any): Promise<any> {\n        return data;\n    }\n}\n`;
        fs.writeFileSync(path.join(projectPath, 'src/services', file), content);
    });

    // Repositories
    const repositories = ['UserRepository.ts', 'ProductRepository.ts'];
    repositories.forEach(file => {
        const content = `import { Pool } from 'mysql2/promise';\nimport { pool } from '../index';\n\nexport class ${file.replace('.ts', '')} {\n    private db: Pool;\n    \n    constructor() {\n        this.db = pool;\n    }\n    \n    // TODO: Implement database operations\n}\n`;
        fs.writeFileSync(path.join(projectPath, 'src/repositories', file), content);
    });

    // Middleware
    const middleware = ['auth.ts', 'errorHandler.ts', 'logger.ts'];
    middleware.forEach(file => {
        const content = `import { Request, Response, NextFunction } from 'express';\n\nexport const ${file.replace('.ts', '')} = (req: Request, res: Response, next: NextFunction) => {\n    // TODO: Implement middleware\n    next();\n};\n`;
        fs.writeFileSync(path.join(projectPath, 'src/middleware', file), content);
    });

    // Config
    const configs = ['database.ts', 'env.ts', 'redis.ts'];
    configs.forEach(file => {
        const content = `export const config = {\n    // TODO: Add configuration\n};\n`;
        fs.writeFileSync(path.join(projectPath, 'src/config', file), content);
    });

    // Utils
    const utils = ['response.ts', 'validator.ts', 'crypto.ts', 'logger.ts'];
    utils.forEach(file => {
        const content = `export const ${file.replace('.ts', '')} = {\n    // TODO: Add utility functions\n};\n`;
        fs.writeFileSync(path.join(projectPath, 'src/utils', file), content);
    });

    // DTOs
    const dtos = ['UserDTO.ts', 'ProductDTO.ts', 'AuthDTO.ts'];
    dtos.forEach(file => {
        const content = `export interface ${file.replace('.ts', '')} {\n    // TODO: Define DTO structure\n}\n`;
        fs.writeFileSync(path.join(projectPath, 'src/dto', file), content);
    });

    // Validators
    const validators = ['userValidator.ts', 'productValidator.ts'];
    validators.forEach(file => {
        const content = `import { z } from 'zod';\n\nexport const validate = (data: any) => {\n    // TODO: Implement validation with zod\n    return true;\n};\n`;
        fs.writeFileSync(path.join(projectPath, 'src/validators', file), content);
    });

    // Routes
    const routes = ['index.ts', 'userRoutes.ts', 'authRoutes.ts', 'productRoutes.ts'];
    routes.forEach(file => {
        const content = `import { Router } from 'express';\nconst router = Router();\n\n// TODO: Add routes\nrouter.get('/', (req, res) => {\n    res.json({ message: '${file} working' });\n});\n\nexport default router;\n`;
        fs.writeFileSync(path.join(projectPath, 'src/routes', file), content);
    });

    // ================================
    // FRONTEND STRUCTURE
    // ================================

    // HTML files
    const htmlFiles = ['index.html', 'about.html', 'contact.html', '404.html'];
    htmlFiles.forEach(file => {
        const content = `<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${file.replace('.html', '')}</title>
    <link rel="stylesheet" href="/css/style.css">
    <link rel="icon" href="/favicon.ico">
</head>
<body>
    <header>
        <nav>
            <a href="/">Home</a>
            <a href="/about.html">About</a>
            <a href="/contact.html">Contact</a>
        </nav>
    </header>
    <main>
        <h1>${file.replace('.html', '')}</h1>
        <p>Welcome to ${projectName}</p>
    </main>
    <footer>
        <p>&copy; 2024 ${projectName}. All rights reserved.</p>
    </footer>
    <script src="/js/main.js"></script>
</body>
</html>`;
        fs.writeFileSync(path.join(projectPath, 'public', file), content);
    });

    // CSS files
    const cssFiles = ['reset.css', 'style.css', 'components.css', 'responsive.css'];
    cssFiles.forEach(file => {
        const content = `/* ${file} */\n\n* {\n    margin: 0;\n    padding: 0;\n    box-sizing: border-box;\n}\n\nbody {\n    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n    line-height: 1.6;\n    color: #333;\n}\n\n/* TODO: Add styles */\n`;
        fs.writeFileSync(path.join(projectPath, 'public/css', file), content);
    });

    // JS files
    const jsFiles = ['main.js', 'api.js', 'utils.js'];
    jsFiles.forEach(file => {
        const content = `// ${file}\n\nconsole.log('${projectName} loaded');\n\n// TODO: Add JavaScript code\n`;
        fs.writeFileSync(path.join(projectPath, 'public/js', file), content);
    });

    // ================================
    // TEST FILES
    // ================================
    
    // Example test
    const exampleTest = `describe('Example Test', () => {
    it('should pass', () => {
        expect(true).toBe(true);
    });
});`;
    fs.writeFileSync(path.join(projectPath, 'tests/unit/example.test.ts'), exampleTest);

    // ================================
    // DOCKER
    // ================================
    
    // Dockerfile
    const dockerfile = `FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM node:20-alpine
WORKDIR /app
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/package*.json ./
RUN npm ci --only=production
EXPOSE 3000
CMD ["npm", "start"]`;
    fs.writeFileSync(path.join(projectPath, 'Dockerfile'), dockerfile);

    // docker-compose.yml
    const dockerCompose = `version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myapp
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data:`;
    fs.writeFileSync(path.join(projectPath, 'docker-compose.yml'), dockerCompose);

    // ================================
    // README
    // ================================
    const readmeContent = `# ${projectName}

## TypeScript Project with Express

### ✨ Features
- 🚀 Express.js with TypeScript
- 🔐 JWT Authentication ready
- 📦 MySQL database integration
- 🐳 Docker support
- ✅ Jest testing setup
- 📝 ESLint + Prettier
- 🔒 Helmet for security
- ⚡ Compression for performance
- 📊 Morgan for logging

### 🚀 Quick Start

\`\`\`bash
# Install dependencies
npm install

# Setup environment variables
cp .env.example .env
# Edit .env with your values

# Run in development mode
npm run dev

# Build for production
npm run build

# Run in production
npm start
\`\`\`

### 🐳 Docker

\`\`\`bash
# Build and run with docker-compose
docker-compose up --build

# Run in background
docker-compose up -d
\`\`\`

### 🧪 Testing

\`\`\`bash
# Run tests
npm test

# Run tests in watch mode
npm run test:watch
\`\`\`

### 📁 Project Structure

\`\`\`
${projectName}/
├── src/
│   ├── config/       # Configuration files
│   ├── controllers/  # Route controllers
│   ├── dto/          # Data Transfer Objects
│   ├── errors/       # Custom error classes
│   ├── events/       # Event handlers
│   ├── jobs/         # Background jobs
│   ├── middleware/   # Express middleware
│   ├── models/       # Database models
│   ├── repositories/ # Data access layer
│   ├── routes/       # API routes
│   ├── services/     # Business logic
│   ├── utils/        # Utility functions
│   └── validators/   # Input validators
├── public/           # Static files
├── tests/            # Test files
├── docs/             # Documentation
├── logs/             # Application logs
├── .env              # Environment variables
├── Dockerfile        # Docker configuration
├── docker-compose.yml
└── package.json
\`\`\`

### 📝 Environment Variables

| Variable | Default | Description |
|----------|---------|-------------|
| PORT | 3000 | Server port |
| DB_HOST | localhost | Database host |
| DB_USER | root | Database user |
| DB_PASSWORD | root | Database password |
| DB_NAME | myapp | Database name |
| JWT_SECRET | - | JWT secret key |
| CORS_ORIGIN | * | CORS allowed origin |

### 📄 License

MIT

---
Generated with ❤️ by **Constellation CLI**
`;
    fs.writeFileSync(path.join(projectPath, 'README.md'), readmeContent);

    // ================================
    // .GITIGNORE
    // ================================
    const gitignoreContent = `# Dependencies
node_modules/
package-lock.json

# Build outputs
dist/
build/
out/

# Environment
.env
.env.local
.env.*.local

# Logs
logs/
*.log
npm-debug.log*

# IDE
.vscode/
.idea/
*.swp
*.swo

# OS
.DS_Store
Thumbs.db

# Test coverage
coverage/
.nyc_output/

# Temporary files
tmp/
temp/
*.tmp

# Uploads
public/uploads/

# Redis
dump.rdb

# MySQL
*.sql
`;
    fs.writeFileSync(path.join(projectPath, '.gitignore'), gitignoreContent);

    console.log(`✅ TypeScript project ${projectName} created successfully at ${projectPath}`);
}