import * as fs from 'fs';
import * as path from 'path';

export async function generateNodeProject(projectPath: string, projectName: string) {
    
    // ================================
    // CRIAR PASTAS PRIMEIRO
    // ================================
    const folders = [
        'src/controllers', 'src/models', 'src/services', 'src/repositories',
        'src/middleware', 'src/config', 'src/utils', 'src/dto', 'src/validators', 'src/routes',
        'src/errors', 'src/events', 'src/jobs', 'src/mails', 'src/subscribers',
        'public/css', 'public/js', 'public/images', 'public/uploads',
        'tests/unit', 'tests/integration', 'tests/e2e',
        'docs/api', 'docs/guides',
        'logs', 'tmp', 'scripts'
    ];
    
    folders.forEach(folder => {
        fs.mkdirSync(path.join(projectPath, folder), { recursive: true });
    });

    // ================================
    // PACKAGE.JSON
    // ================================
    const packageJson = {
        name: projectName,
        version: "1.0.0",
        description: `Generated by Constellation CLI`,
        main: "server.js",
        scripts: {
            "start": "node server.js",
            "dev": "nodemon server.js",
            "test": "jest",
            "test:watch": "jest --watch",
            "lint": "eslint src/**/*.js",
            "lint:fix": "eslint src/**/*.js --fix",
            "format": "prettier --write \"src/**/*.js\""
        },
        dependencies: {
            "express": "^4.18.2",
            "mysql2": "^3.6.0",
            "bcrypt": "^5.1.0",
            "jsonwebtoken": "^9.0.0",
            "express-rate-limit": "^7.1.0",
            "cors": "^2.8.5",
            "dotenv": "^16.3.0",
            "helmet": "^7.1.0",
            "compression": "^1.7.4",
            "morgan": "^1.10.0",
            "express-async-errors": "^3.1.1",
            "uuid": "^9.0.1",
            "dayjs": "^1.11.10",
            "axios": "^1.6.2",
            "multer": "^1.4.5-lts.1",
            "nodemailer": "^6.9.7",
            "winston": "^3.11.0"
        },
        devDependencies: {
            "nodemon": "^3.0.1",
            "jest": "^29.7.0",
            "supertest": "^6.3.3",
            "eslint": "^8.55.0",
            "prettier": "^3.1.0"
        },
        keywords: ["api", "rest", "backend", "express", "nodejs"],
        author: "",
        license: "MIT"
    };
    fs.writeFileSync(path.join(projectPath, 'package.json'), JSON.stringify(packageJson, null, 2));

    // ================================
    // .ENV FILE
    // ================================
    const envContent = `NODE_ENV=development
PORT=3000
APP_NAME=${projectName}
APP_URL=http://localhost:3000

DB_HOST=localhost
DB_PORT=3306
DB_USER=root
DB_PASSWORD=root
DB_NAME=myapp

JWT_SECRET=mysecretkey
JWT_EXPIRES_IN=7d

REDIS_HOST=localhost
REDIS_PORT=6379
REDIS_PASSWORD=

MAIL_HOST=smtp.gmail.com
MAIL_PORT=587
MAIL_USER=your-email@gmail.com
MAIL_PASSWORD=your-password
MAIL_FROM=noreply@${projectName}.com

CORS_ORIGIN=http://localhost:3000
RATE_LIMIT_WINDOW=15
RATE_LIMIT_MAX=100

LOG_LEVEL=debug
`;
    fs.writeFileSync(path.join(projectPath, '.env'), envContent);
    fs.writeFileSync(path.join(projectPath, '.env.example'), envContent.replace(/=.*/g, '='));

    // ================================
    // SERVER.JS
    // ================================
    const serverContent = `const express = require('express');
const mysql = require('mysql2');
const bcrypt = require('bcrypt');
const jwt = require('jsonwebtoken');
const rateLimit = require('express-rate-limit');
const cors = require('cors');
const dotenv = require('dotenv');
const helmet = require('helmet');
const compression = require('compression');
const morgan = require('morgan');
require('express-async-errors');
const path = require('path');

dotenv.config();

const app = express();
const PORT = process.env.PORT || 3000;

// Middlewares
app.use(helmet());
app.use(compression());
app.use(cors({
    origin: process.env.CORS_ORIGIN || '*',
    credentials: true
}));
app.use(morgan('combined'));
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use(express.static(path.join(__dirname, 'public')));

// Rate limiting
const limiter = rateLimit({
    windowMs: (parseInt(process.env.RATE_LIMIT_WINDOW) || 15) * 60 * 1000,
    max: parseInt(process.env.RATE_LIMIT_MAX) || 100,
    message: { error: 'Too many requests, please try again later.' }
});
app.use('/api/', limiter);

// Database connection pool
const pool = mysql.createPool({
    host: process.env.DB_HOST || 'localhost',
    port: parseInt(process.env.DB_PORT) || 3306,
    user: process.env.DB_USER || 'root',
    password: process.env.DB_PASSWORD || '',
    database: process.env.DB_NAME || 'myapp',
    waitForConnections: true,
    connectionLimit: 10,
    queueLimit: 0,
    enableKeepAlive: true,
    keepAliveInitialDelay: 0
});

// Test database connection
pool.getConnection()
    .then(connection => {
        console.log('✅ Database connected successfully');
        connection.release();
    })
    .catch(err => {
        console.error('❌ Database connection failed:', err.message);
    });

// Routes
app.get('/', (req, res) => {
    res.json({ 
        message: 'API is running!', 
        version: '1.0.0',
        environment: process.env.NODE_ENV || 'development',
        endpoints: {
            health: 'GET /health',
            api: 'GET /api'
        }
    });
});

app.get('/health', (req, res) => {
    res.json({ 
        status: 'ok', 
        timestamp: new Date().toISOString(),
        uptime: process.uptime()
    });
});

app.get('/api', (req, res) => {
    res.json({ message: 'API v1 - Working!' });
});

// 404 handler
app.use((req, res) => {
    res.status(404).json({ 
        error: 'Route not found',
        path: req.originalUrl
    });
});

// Global error handler
app.use((err, req, res, next) => {
    console.error('Error:', err.stack);
    const status = err.status || 500;
    const message = err.message || 'Internal server error';
    
    res.status(status).json({ 
        error: message,
        status,
        timestamp: new Date().toISOString()
    });
});

// Start server
const server = app.listen(PORT, () => {
    console.log(\`🚀 Server running on port \${PORT}\`);
    console.log(\`🔗 http://localhost:\${PORT}\`);
});

// Graceful shutdown
process.on('SIGTERM', () => {
    console.log('SIGTERM signal received: closing HTTP server');
    server.close(() => {
        console.log('HTTP server closed');
        pool.end().then(() => {
            console.log('Database connection pool closed');
            process.exit(0);
        });
    });
});

module.exports = { app, pool, server };`;
    fs.writeFileSync(path.join(projectPath, 'server.js'), serverContent);

    // ================================
    // BACKEND STRUCTURE (WITH CONTENT)
    // ================================
    
    // Controllers
    const controllers = ['HomeController.js', 'UserController.js', 'AuthController.js'];
    controllers.forEach(file => {
        const content = `// ${file}\n\nclass ${file.replace('.js', '')} {\n    // TODO: Implement methods\n    \n    async index(req, res) {\n        return res.json({ message: '${file} working' });\n    }\n}\n\nmodule.exports = new ${file.replace('.js', '')}();\n`;
        fs.writeFileSync(path.join(projectPath, 'src/controllers', file), content);
    });

    // Models
    const models = ['UserModel.js', 'ProductModel.js', 'AuthModel.js'];
    models.forEach(file => {
        const content = `// ${file}\n\nclass ${file.replace('.js', '')} {\n    // TODO: Define model structure\n}\n\nmodule.exports = ${file.replace('.js', '')};\n`;
        fs.writeFileSync(path.join(projectPath, 'src/models', file), content);
    });

    // Services
    const services = ['UserService.js', 'AuthService.js', 'ProductService.js'];
    services.forEach(file => {
        const content = `// ${file}\n\nclass ${file.replace('.js', '')} {\n    // TODO: Implement business logic\n    \n    async execute(data) {\n        return data;\n    }\n}\n\nmodule.exports = new ${file.replace('.js', '')}();\n`;
        fs.writeFileSync(path.join(projectPath, 'src/services', file), content);
    });

    // Repositories
    const repositories = ['UserRepository.js', 'ProductRepository.js'];
    repositories.forEach(file => {
        const content = `// ${file}\n\nconst pool = require('../../server').pool;\n\nclass ${file.replace('.js', '')} {\n    constructor() {\n        this.db = pool;\n    }\n    \n    // TODO: Implement database operations\n}\n\nmodule.exports = new ${file.replace('.js', '')}();\n`;
        fs.writeFileSync(path.join(projectPath, 'src/repositories', file), content);
    });

    // Middleware
    const middleware = ['auth.js', 'errorHandler.js', 'logger.js'];
    middleware.forEach(file => {
        const content = `// ${file}\n\nconst ${file.replace('.js', '')} = (req, res, next) => {\n    // TODO: Implement middleware\n    next();\n};\n\nmodule.exports = ${file.replace('.js', '')};\n`;
        fs.writeFileSync(path.join(projectPath, 'src/middleware', file), content);
    });

    // Config
    const configs = ['database.js', 'env.js'];
    configs.forEach(file => {
        const content = `// ${file}\n\nconst config = {\n    // TODO: Add configuration\n};\n\nmodule.exports = config;\n`;
        fs.writeFileSync(path.join(projectPath, 'src/config', file), content);
    });

    // Utils
    const utils = ['response.js', 'validator.js', 'crypto.js', 'logger.js'];
    utils.forEach(file => {
        const content = `// ${file}\n\nconst ${file.replace('.js', '')} = {\n    // TODO: Add utility functions\n};\n\nmodule.exports = ${file.replace('.js', '')};\n`;
        fs.writeFileSync(path.join(projectPath, 'src/utils', file), content);
    });

    // DTOs
    const dtos = ['UserDTO.js', 'ProductDTO.js', 'AuthDTO.js'];
    dtos.forEach(file => {
        const content = `// ${file}\n\nclass ${file.replace('.js', '')} {\n    // TODO: Define DTO structure\n}\n\nmodule.exports = ${file.replace('.js', '')};\n`;
        fs.writeFileSync(path.join(projectPath, 'src/dto', file), content);
    });

    // Validators
    const validators = ['userValidator.js', 'productValidator.js'];
    validators.forEach(file => {
        const content = `// ${file}\n\nconst validate = (data) => {\n    // TODO: Implement validation\n    return true;\n};\n\nmodule.exports = { validate };\n`;
        fs.writeFileSync(path.join(projectPath, 'src/validators', file), content);
    });

    // Routes
    const routes = ['index.js', 'userRoutes.js', 'authRoutes.js', 'productRoutes.js'];
    routes.forEach(file => {
        const content = `// ${file}\n\nconst router = require('express').Router();\n\n// TODO: Add routes\nrouter.get('/', (req, res) => {\n    res.json({ message: '${file} working' });\n});\n\nmodule.exports = router;\n`;
        fs.writeFileSync(path.join(projectPath, 'src/routes', file), content);
    });

    // ================================
    // FRONTEND STRUCTURE
    // ================================

    // HTML files
    const htmlFiles = ['index.html', 'about.html', 'contact.html', '404.html'];
    htmlFiles.forEach(file => {
        const content = `<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${file.replace('.html', '')}</title>
    <link rel="stylesheet" href="/css/style.css">
</head>
<body>
    <header>
        <nav>
            <a href="/">Home</a>
            <a href="/about.html">About</a>
            <a href="/contact.html">Contact</a>
        </nav>
    </header>
    <main>
        <h1>${file.replace('.html', '')}</h1>
        <p>Welcome to ${projectName}</p>
    </main>
    <footer>
        <p>&copy; 2024 ${projectName}. All rights reserved.</p>
    </footer>
    <script src="/js/main.js"></script>
</body>
</html>`;
        fs.writeFileSync(path.join(projectPath, 'public', file), content);
    });

    // CSS files
    const cssFiles = ['reset.css', 'style.css', 'components.css', 'responsive.css'];
    cssFiles.forEach(file => {
        const content = `/* ${file} */\n\n* {\n    margin: 0;\n    padding: 0;\n    box-sizing: border-box;\n}\n\nbody {\n    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n    line-height: 1.6;\n    color: #333;\n}\n\n/* TODO: Add styles */\n`;
        fs.writeFileSync(path.join(projectPath, 'public/css', file), content);
    });

    // JS files
    const jsFiles = ['main.js', 'api.js', 'utils.js'];
    jsFiles.forEach(file => {
        const content = `// ${file}\n\nconsole.log('${projectName} loaded');\n\n// TODO: Add JavaScript code\n`;
        fs.writeFileSync(path.join(projectPath, 'public/js', file), content);
    });

    // ================================
    // TEST FILES
    // ================================
    
    const exampleTest = `describe('Example Test', () => {
    it('should pass', () => {
        expect(true).toBe(true);
    });
});`;
    fs.writeFileSync(path.join(projectPath, 'tests/unit/example.test.js'), exampleTest);

    // ================================
    // DOCKER
    // ================================
    
    const dockerfile = `FROM node:18-alpine
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
EXPOSE 3000
CMD ["npm", "start"]`;
    fs.writeFileSync(path.join(projectPath, 'Dockerfile'), dockerfile);

    const dockerCompose = `version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myapp
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:`;
    fs.writeFileSync(path.join(projectPath, 'docker-compose.yml'), dockerCompose);

    // ================================
    // README
    // ================================
    const readmeContent = `# ${projectName}

## Node.js/Express Project

### ✨ Features
- 🚀 Express.js framework
- 🔐 JWT Authentication ready
- 📦 MySQL database integration
- 🐳 Docker support
- ✅ Jest testing setup
- 📝 ESLint + Prettier
- 🔒 Helmet for security
- ⚡ Compression for performance
- 📊 Morgan for logging

### 🚀 Quick Start

\`\`\`bash
# Install dependencies
npm install

# Setup environment variables
cp .env.example .env
# Edit .env with your values

# Run in development mode
npm run dev

# Run in production
npm start
\`\`\`

### 🐳 Docker

\`\`\`bash
docker-compose up --build
\`\`\`

### 📁 Project Structure

\`\`\`
${projectName}/
├── src/
│   ├── config/       # Configuration files
│   ├── controllers/  # Route controllers
│   ├── dto/          # Data Transfer Objects
│   ├── middleware/   # Express middleware
│   ├── models/       # Database models
│   ├── repositories/ # Data access layer
│   ├── routes/       # API routes
│   ├── services/     # Business logic
│   ├── utils/        # Utility functions
│   └── validators/   # Input validators
├── public/           # Static files
├── tests/            # Test files
├── .env              # Environment variables
├── Dockerfile
├── docker-compose.yml
└── package.json
\`\`\`

### 📄 License

MIT

---
Generated with ❤️ by **Constellation CLI**
`;
    fs.writeFileSync(path.join(projectPath, 'README.md'), readmeContent);

    // ================================
    // .GITIGNORE
    // ================================
    const gitignoreContent = `node_modules/
.env
.env.local
logs/
*.log
dist/
coverage/
.DS_Store
Thumbs.db
public/uploads/
tmp/
`;
    fs.writeFileSync(path.join(projectPath, '.gitignore'), gitignoreContent);

    console.log(`✅ Node.js project ${projectName} created successfully at ${projectPath}`);
}